require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const service = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const anonKey = process.env.SUPABASE_ANON_KEY;
const apiBase = 'http://127.0.0.1:5000/api';
const suffix = `${Date.now()}-${Math.floor(Math.random() * 10000)}`;
const userIds = []; const results = []; let documentId;
function assert(name, pass, detail = '') { results.push({ name, pass: Boolean(pass), detail }); if (!pass) throw new Error(`${name}: ${detail}`); }
function parsePgVector(value) {
  if (typeof value !== 'string') return null;
  const normalized = value.trim();
  if (!/^\[[\s\S]*\]$/.test(normalized)) return null;
  const values = normalized.slice(1, -1).split(',').map(part => Number(part.trim()));
  return values.length > 0 && values.every(Number.isFinite) ? values : null;
}
async function call(path, options = {}) { const response = await fetch(`${apiBase}${path}`, options); const text = await response.text(); let body = text; try { body = text ? JSON.parse(text) : null; } catch {} return { status: response.status, body, headers: Object.fromEntries(response.headers) }; }
async function provision(label, role = 'student') {
  const email = `eduquery-${label}-${suffix}@example.test`; const password = `Pass!${label}${suffix}`;
  const created = await service.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { full_name: label } });
  if (created.error) throw created.error; const id = created.data.user.id; userIds.push(id);
  if (role === 'admin') { const update = await service.from('profiles').update({ role: 'admin' }).eq('id', id); if (update.error) throw update.error; }
  const client = createClient(process.env.SUPABASE_URL, anonKey); const signedIn = await client.auth.signInWithPassword({ email, password }); if (signedIn.error) throw signedIn.error;
  return { id, email, password, client, token: signedIn.data.session.access_token };
}
const bearer = token => ({ Authorization: `Bearer ${token}` });
async function run() {
  const columns = await service.from('documents').select('id,processing_status,processing_error').limit(1); assert('schema columns', !columns.error, columns.error?.message);
  const registered = await provision('registration'); const trigger = await service.from('profiles').select('id,role').eq('id', registered.id).single(); assert('registration profile trigger', !trigger.error && trigger.data.role === 'student', trigger.error?.message || trigger.data?.role);
  const invalidClient = createClient(process.env.SUPABASE_URL, anonKey); const invalid = await invalidClient.auth.signInWithPassword({ email: registered.email, password: 'incorrect' }); assert('invalid login', Boolean(invalid.error), invalid.error?.message);
  const studentA = await provision('student-a'); const studentB = await provision('student-b'); const admin = await provision('admin', 'admin');
  let response = await call('/auth/me', { headers: bearer(studentA.token) }); assert('student login/profile', response.status === 200 && response.body.profile.role === 'student', JSON.stringify(response));
  response = await call('/auth/me', { headers: bearer(admin.token) }); assert('admin login/profile', response.status === 200 && response.body.profile.role === 'admin', JSON.stringify(response));
  assert('unauthenticated api rejection', (await call('/auth/me')).status === 401); assert('student admin blocked', (await call('/admin/stats', { headers: bearer(studentA.token) })).status === 403); assert('admin stats access', (await call('/admin/stats', { headers: bearer(admin.token) })).status === 200);
  const ownProfile = await studentA.client.from('profiles').select('id').eq('id', studentA.id); const foreignProfile = await studentA.client.from('profiles').select('id').eq('id', studentB.id); assert('RLS own profile', !ownProfile.error && ownProfile.data.length === 1, ownProfile.error?.message); assert('RLS foreign profile hidden', !foreignProfile.error && foreignProfile.data.length === 0, foreignProfile.error?.message || JSON.stringify(foreignProfile.data));
  assert('unauthenticated documents blocked', (await call('/documents')).status === 401); assert('unauthenticated upload blocked', (await call('/documents/upload', { method: 'POST' })).status === 401);
  response = await call('/chat/query', { method: 'POST', headers: { ...bearer(studentA.token), 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'What official information is available?' }) }); assert('conversation creation', response.status === 200 && response.body.conversation_id, JSON.stringify(response)); const conversationId = response.body.conversation_id;
  response = await call(`/chat/conversations/${conversationId}`, { headers: bearer(studentA.token) }); assert('conversation retrieval', response.status === 200 && response.body.messages.length >= 2, JSON.stringify(response)); assert('conversation isolation', (await call(`/chat/conversations/${conversationId}`, { headers: bearer(studentB.token) })).status === 403);
  const form = new FormData(); form.append('title', 'Live Attendance Policy'); form.append('category', 'Academics'); form.append('department', 'General'); form.append('file', new Blob(['Students must maintain at least 75 percent attendance to be eligible for semester examinations. Attendance shortages require approval from the academic office.'], { type: 'text/plain' }), 'attendance-policy.txt');
  response = await call('/documents/upload', { method: 'POST', headers: bearer(admin.token), body: form }); assert('multipart document upload/indexing', response.status === 200 && response.body.success && response.body.document.processing_status === 'indexed', JSON.stringify(response)); documentId = response.body.document.id;
  const document = await service.from('documents').select('processing_status,chunk_count').eq('id', documentId).single(); const chunks = await service.from('document_chunks').select('id,embedding').eq('document_id', documentId); const parsedVectors = chunks.data?.map(chunk => parsePgVector(chunk.embedding)); const vectorDetail = JSON.stringify({ status: document.data?.processing_status, chunkCount: chunks.data?.length, vectors: chunks.data?.map((chunk, index) => ({ type: typeof chunk.embedding, rawLength: typeof chunk.embedding === 'string' ? chunk.embedding.length : null, parsedLength: parsedVectors?.[index]?.length ?? null, prefix: typeof chunk.embedding === 'string' ? chunk.embedding.trim().slice(0, 2) : null, suffix: typeof chunk.embedding === 'string' ? chunk.embedding.trim().slice(-2) : null })) }); assert('database vector insertion', !document.error && document.data.processing_status === 'indexed' && parsedVectors?.length > 0 && parsedVectors.every(vector => vector?.length === 768 && vector.every(Number.isFinite)), document.error?.message || chunks.error?.message || vectorDetail);
  response = await call('/documents', { headers: bearer(admin.token) }); assert('document listing', response.status === 200 && response.body.documents.some(document => document.id === documentId), JSON.stringify(response)); response = await call(`/documents/${documentId}`, { headers: bearer(studentA.token) }); assert('document preview', response.status === 200 && response.body.chunks.length > 0, JSON.stringify(response));
  response = await call('/chat/query', { method: 'POST', headers: { ...bearer(studentA.token), 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'What attendance is required for semester examinations?' }) }); assert('RAG retrieval/generation/citations', response.status === 200 && !response.body.is_unknown && response.body.citations?.some(citation => citation.document_id === documentId), JSON.stringify(response)); const messageId = response.body.message_id;
  const persistedMessage = await service.from('messages').select('conversation_id,citations,is_unknown').eq('id', messageId).single(); assert('citation and message persistence', !persistedMessage.error && persistedMessage.data.citations?.some(citation => citation.document_id === documentId) && persistedMessage.data.is_unknown === false, persistedMessage.error?.message || JSON.stringify(persistedMessage.data));
  assert('feedback foreign user rejected', (await call('/chat/feedback', { method: 'POST', headers: { ...bearer(studentB.token), 'Content-Type': 'application/json' }, body: JSON.stringify({ message_id: messageId, feedback: 'positive' }) })).status === 403); assert('feedback owner accepted', (await call('/chat/feedback', { method: 'POST', headers: { ...bearer(studentA.token), 'Content-Type': 'application/json' }, body: JSON.stringify({ message_id: messageId, feedback: 'positive' }) })).status === 200);
  response = await call('/admin/stats', { headers: bearer(admin.token) }); assert('live stats', response.status === 200 && response.body.stats.total_documents >= 1 && response.body.stats.total_vector_chunks >= 1, JSON.stringify(response)); assert('student deletion blocked', (await call(`/documents/${documentId}`, { method: 'DELETE', headers: bearer(studentA.token) })).status === 403); assert('admin deletion', (await call(`/documents/${documentId}`, { method: 'DELETE', headers: bearer(admin.token) })).status === 200); const remaining = await service.from('document_chunks').select('id').eq('document_id', documentId); assert('deletion chunk cleanup', !remaining.error && remaining.data.length === 0, remaining.error?.message || JSON.stringify(remaining.data)); response = await call('/admin/stats', { headers: bearer(admin.token) }); assert('stats update after deletion', response.status === 200 && response.body.stats.total_documents >= 0 && response.body.stats.total_vector_chunks >= 0, JSON.stringify(response)); documentId = null;
  await studentA.client.auth.signOut(); const session = await studentA.client.auth.getSession(); assert('logout cleanup', !session.data.session, JSON.stringify(session.data));
}
run().catch(error => results.push({ name: 'failure', pass: false, detail: `${error.message}\n${error.stack || ''}` })).finally(async () => { if (documentId) await service.from('documents').delete().eq('id', documentId); for (const id of userIds) await service.auth.admin.deleteUser(id); console.log(JSON.stringify(results, null, 2)); if (results.some(result => !result.pass)) process.exitCode = 1; });
